# Matrices and Vectors

Matrices are 2-dimensional arrays:
> $
  \left[ {\begin{array}{cc}
   a & b & c \\
   d & e & f \\
   g & h & i \\
   j & k & l \\
  \end{array} } \right]
$


The above matrix has four rows and three columns, so it is a 4 x 3 matrix.

A vector is a matrix with one column and many rows:

> $
  \left[ {\begin{array}{cc}
   w \\
   x \\
   y \\
   z \\
  \end{array} } \right]
$

So vectors are a subset of matrices. The above vector is a 4 x 1 matrix.

Notation and terms:

* $A_{ij}$ refers to the element in the ith row and jth column of matrix A.
* A vector with 'n' rows is referred to as an 'n'-dimensional vector.
* $v_i$ refers to the element in the ith row of the vector.
* In general, all our vectors and matrices will be 1-indexed. Note that for some programming languages, the arrays are 0-indexed.
* Matrices are usually denoted by uppercase names while vectors are lowercase.
* "Scalar" means that an object is a single value, not a vector or matrix.
* $\mathbb{R}$ refers to the set of scalar real numbers.
* $\mathbb{R^n}$ refers to the set of n-dimensional vectors of real numbers.

Experiment below with the Octave/Matlab commands for matrix and vector initalization 
```octave
% The ; denotes we are going back to a new row.
A = [1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12]
% Initialize a vector 
v = [1;2;3] 
% Get the dimension of the matrix A where m = rows and n = columns
[m,n] = size(A)
% You could also store it this way
dim_A = size(A)
% Get the dimension of the vector v 
dim_v = size(v)
% Now let's index into the 2nd row 3rd column of matrix A
A_23 = A(2,3)
```

In [54]:
import numpy as np


In [55]:
#Initialize a matrix (4,3)
A= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A,"\nMatrix of Shape:",A.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
Matrix of Shape: (4, 3)


In [56]:
#Initialize a vector
v = np.array([1,2,3])
print(v,"\nVector of Shape:",v.shape)


[1 2 3] 
Vector of Shape: (3,)


In [57]:
#Now let's get the 2nd row 3rd column of matrix A which is 6
A_23 = A[1,2]
A_23

6

## Addition and Scalar Multiplication

Addition and subtraction are element-wise, so you simply add or subtract each corresponding element:
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ \end{array} } \right] + x := \left[ {\begin{array}{cc}a+x & b+x \\ c+x & d+x\\ \end{array} } \right]$

Subtracting Matrices:
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ \end{array} } \right] - x := \left[ {\begin{array}{cc}a-x & b-x \\ c-x & d-x\\ \end{array} } \right]$

To add or subtract two matrices, their dimensions must be the same.

In scalar multiplication, we simply multiply every element by the scalar value:
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ \end{array} } \right] \times x := \left[ {\begin{array}{cc}a\times x & b\times x \\ c\times x & d\times x\\ \end{array} } \right]$

In scalar division, we simply divide every element by the scalar value:
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ \end{array} } \right]/ x := \left[ {\begin{array}{cc}\frac{a}{x} & \frac{b}{x} \\ \frac{c}{x} & \frac{d}{x}\\ \end{array} } \right]$

Experiment below with the Octave/Matlab commands for matrix addition and scalar multiplication.
```octave
% Initialize matrix A and B 
A = [1, 2, 4; 5, 3, 2]
B = [1, 3, 4; 1, 1, 1]
% Initialize constant s 
s = 2
% See how element-wise addition works
add_AB = A + B 
% See how element-wise subtraction works
sub_AB = A - B
% See how scalar multiplication works
mult_As = A * s
% Divide A by s
div_As = A / s
% What happens if we have a Matrix + scalar?
add_As = A + s
```

In [58]:
A= np.array([[1,2,4],[5,3,2]])
B= np.array([[1,3,4],[1,1,1]])
s=2
add_AB = A + B
print('A+B:',add_AB,'\n')
sub_AB = A - B
print('A-B:',sub_AB,'\n')
mult_As = A * s
print('A*s:',mult_As,'\n')
div_As = A / s
print('A/s:',div_As,'\n')
add_As = A + s
print('A + s:',add_As,'\n')

A+B: [[2 5 8]
 [6 4 3]] 

A-B: [[ 0 -1  0]
 [ 4  2  1]] 

A*s: [[ 2  4  8]
 [10  6  4]] 

A/s: [[0.50000 1.00000 2.00000]
 [2.50000 1.50000 1.00000]] 

A + s: [[3 4 6]
 [7 5 4]] 



## Matrix-Vector Multiplication (Dot Product)

We map the column of the vector onto each row of the matrix, multiplying each element and summing the result.
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ e & f\\ \end{array} } \right] * \left[ {\begin{array}{cc}x \\ y\\ \end{array} } \right] := \left[ {\begin{array}{cc}a*x + b*y \\ c*x + d*y\\ e*x + f*y\\ \end{array} } \right]$

The result is a vector. The number of columns of the matrix must equal the number of rows of the vector.

An m x n matrix multiplied by an n x 1 vector results in an m x 1 vector.

Below is an example of a matrix-vector multiplication. Make sure you understand how the multiplication works. 
```octave
% Initialize matrix A 
A = [1, 2, 3; 4, 5, 6;7, 8, 9] 
% Initialize vector v 
v = [1; 1; 1] 
% Multiply A * v
Av = A * v
```

In [59]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
v=[1,1,1]
Av=np.dot(A,v)
print('A.v:',Av)

A.v: [ 6 15 24]


## Matrix-Matrix Multiplication

We multiply two matrices by breaking it into several vector multiplications and concatenating the result.
> $\left[ {\begin{array}{cc}a & b \\ c & d\\ e & f\\ \end{array} } \right] * \left[ {\begin{array}{cc}w & x \\ y * z\\ \end{array} } \right] := \left[ {\begin{array}{cc}a*w + b*y & a*x + b*z\\ c*w + d*y & c*x + d*z\\ e*w + f*y & e*x + f*z\\ \end{array} } \right]$


An m x n matrix multiplied by an n x o matrix results in an m x o matrix. In the above example, a 3 x 2 matrix times a 2 x 2 matrix resulted in a 3 x 2 matrix.

To multiply two matrices, the number of columns of the first matrix must equal the number of rows of the second matrix.

For example:
```octave
% Initialize a 3 by 2 matrix 
A = [1, 2; 3, 4;5, 6]
% Initialize a 2 by 1 matrix 
B = [1; 2] 
% We expect a resulting matrix of (3 by 2)*(2 by 1) = (3 by 1) 
mult_AB = A*B
% Make sure you understand why we got that result
```

In [60]:
A= np.array([[1,2],[3,4],[5,6]])
B=[[1],[2]]
mult_AB = np.dot(A,B)
print('A*B:',mult_AB)

A*B: [[ 5]
 [11]
 [17]]


### Matrix Multiplication Properties

* Matrices are not commutative: $ A∗B≠B∗A $
* Matrices are associative: $ (A∗B)∗C=A∗(B∗C) $

The __identity matrix__, when multiplied by any matrix of the same dimensions, results in the original matrix. It's just like multiplying numbers by 1. The identity matrix simply has 1's on the diagonal (upper left to lower right diagonal) and 0's elsewhere.
$$\left[ {\begin{array}{cc}1 & 0 & 0 \\ 0 & 1 & 0\\ 0 & 0 & 1\\ \end{array} } \right]$$

When multiplying the identity matrix after some matrix (A∗I), the square identity matrix's dimension should match the other matrix's columns. When multiplying the identity matrix before some other matrix (I∗A), the square identity matrix's dimension should match the other matrix's rows.

```octave
% Initialize random matrices A and B 
A = [1,2;4,5]
B = [1,1;0,2]
% Initialize a 2 by 2 identity matrix
I = eye(2)
% The above notation is the same as I = [1,0;0,1]
% What happens when we multiply I*A ? 
IA = I*A 
% How about A*I ? 
AI = A*I 
% Compute A*B 
AB = A*B 
% Is it equal to B*A? 
BA = B*A 
% Note that IA = AI but AB != BA
```

In [61]:
A = np.array([[1,2],[4,5]])
B = np.array([[1,1],[0,2]])
I= np.identity(2,dtype='int64')
IA=np.dot(I,A)
AI=np.dot(A,I)
AB=np.dot(A,B)
BA=np.dot(B,A)
print('A:\n',A,'\nB:\n',B,'\nI:\n',I)
print('IA:\n',IA,'\nAI:\n',AI)
print('AB:\n',AB,'\nBA:\n',BA)

A:
 [[1 2]
 [4 5]] 
B:
 [[1 1]
 [0 2]] 
I:
 [[1 0]
 [0 1]]
IA:
 [[1 2]
 [4 5]] 
AI:
 [[1 2]
 [4 5]]
AB:
 [[ 1  5]
 [ 4 14]] 
BA:
 [[ 5  7]
 [ 8 10]]


## Inverse and Transpose

The `inverse` of a matrix A is denoted $A^{-1}$. Multiplying by the inverse results in the identity matrix.

A non square matrix does not have an inverse matrix. We can compute inverses of matrices in octave with the `pinv(A)` function , in Matlab with the `inv(A)` function and in python with the `np.linalg.inv`. Matrices that don't have an inverse are singular or degenerate.

The `transposition` of a matrix is like rotating the matrix 90° in clockwise direction and then reversing it. We can compute transposition of matrices in matlab with the `transpose(A)` function or `A'` and and in python with the `A.T`:
> $A = \left[ {\begin{array}{cc}a & b \\ c & d\\ e & f\\ \end{array} } \right]$ 

> $A^{T} = \left[ {\begin{array}{cc}a & c & e\\ b & d & f\\ \end{array} } \right]$


In other words:

$A_{ij} = A^T_{ji}$

For example:
```octave
% Initialize matrix A 
A = [1,2,0;0,5,6;7,0,9]
% Transpose A 
A_trans = A' 
% Take the inverse of A 
A_inv = inv(A)
% What is A^(-1)*A? 
A_invA = inv(A)*A
```

In [62]:
A = np.array([[1,2,0],[0,5,6],[7,0,9]])
A_trans = A.T #Transpose A 
A_inv = np.linalg.inv(A)#Take the inverse of A 
A_invA = np.dot(A_inv, A)# What is A^(-1)*A? 
print('A:\n',A,'\nA_trans:\n',A_trans,'\nA_inv:\n',A_inv)
np.set_printoptions(formatter={'float': lambda x: "{0:0.5f}".format(x)})
print('A_invA:\n',A_invA)

A:
 [[1 2 0]
 [0 5 6]
 [7 0 9]] 
A_trans:
 [[1 0 7]
 [2 5 0]
 [0 6 9]] 
A_inv:
 [[0.34884 -0.13953 0.09302]
 [0.32558 0.06977 -0.04651]
 [-0.27132 0.10853 0.03876]]
A_invA:
 [[1.00000 0.00000 0.00000]
 [0.00000 1.00000 0.00000]
 [-0.00000 0.00000 1.00000]]
